development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_bank_development
  pool: 5
  username: bank
  password: bank

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_bank_test
  pool: 5
  username: bank
  password: bank
